spring:
  application:
    name: inbox-app

  data:
    cassandra:
      keyspace-name: main
      username: jYmzykKMrdGWEABoSHkayIUI
      password: QfgoBZh0KCRfrxDnu0x2Ql.6yi5A7Zqhm1NCMENk3v94sQ9qxpxZZuYkt99_vQhHDWMgeq16YRyxLoM26vfgafBdSnIO.c8kxEt5ylAI+39MkKL3OBnYm7BB6HXl6RlD
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.23288a918ce72621
            client-secret: 0abdca9c29ff04aa33e685f4b812bc16ef38bb38

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra:
  db:
    id: 2acf8784-963a-463d-99a0-beb5897047d3-1
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:jYmzykKMrdGWEABoSHkayIUI:073b08eb4da655b094b7ec28b48d3a31341aab6fefb998ccc41e71be3531789d
